### ISSUE TITLE
[TASK] Clarify some Things (re #426)

### ISSUE THREAD

**Issue by lazaridiscom** [vmware/concord-bft#430]
(draft, me executing this most possibly within the next days)

re #426 

## Task

Document any findings from within issue #426 (especially https://github.com/vmware/concord-bft/issues/426#issuecomment-594690171), thus visitors have the right expectations, and can find information/documentation faster.

### Steps

- [x] #439 Consider creating a `1.0 Milestone`
- [x] Add a clarification re "Some docs we have written are not quite ready for open source and need to be cleaned and stripped of proprietary information before being shared."
- [x] Mention the availability of "in-code" documentation with the readme
- [x] Ensure that in-code documentation (which is a good thing), is mentioned from an in-unit (folder) README, so a visitor browsing the code finds it.
- [x] clarify that there is a business-unit behind the code, which prioritizes business customers (this is nothing bad, of course, should be mentioned to avoid false expectations)
- [x] clarify "All work done for paying customers relating to the BFT code becomes open source and is made freely available. "
- [x] clarify "status" (e.g.: "is used in production by multiple yxz)
- [x] Consider providing a link or interested business-customers (e.g. "custom development" on vmware website)
- [ ] ...

**Comment by teoparvanov** [comment]
Thank you @lazaridiscom , let's work together on enhancing the list of necessary steps.

**Comment by teoparvanov** [comment]
I think we should also enhance the existing design document:
https://github.com/vmware/concord-bft/blob/master/docs/design.md

We need additional sections on fast/slow path, as well as view change at a minimum.

**Comment by lazaridiscom** [comment]
@teoparvanov , I'll focus for now just on #426, to get this "out of my system". I don't need help for this for now, just when it comes to PRs or questions.

**Comment by teoparvanov** [comment]
Alright, makes sense.

**Comment by lazaridiscom** [comment]
> I think we should also enhance the existing design document:
> https://github.com/vmware/concord-bft/blob/master/docs/design.md

@teoparvanov , the main problem with this is that it is generally preferable to have a architectural-overview diagram.

I'll come back to this should I reach this subsystem.

**Comment by salieri11** [comment]
Great points, @lazaridiscom !! You are welcome to work on it and to open PR where we can discuss it.

**Comment by lazaridiscom** [comment]
Re "concord-bft commercial development/support", is there any link that could be provided?

**Comment by lazaridiscom** [comment]
closing in favor of  #438 and #439 (team needs to execute those).
